# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 23:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app_2', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='miapp2model',
            old_name='campo',
            new_name='nombre',
        ),
    ]
